# Generated by Django 4.1.2 on 2022-11-11 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Access",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("approved", models.BooleanField(default=False)),
                ("preshared_secret", models.BinaryField()),
                ("secret", models.BinaryField()),
                ("parameters", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=200)),
                ("offboarding", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["email"], name="sekuracore__email_a8f4c2_idx"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["name", "secret", "preshared_secret"], name="sekuracore__name_b89a3a_idx"),
        ),
        migrations.AddField(
            model_name="access",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="access", to="sekuracore.agent"
            ),
        ),
        migrations.AddField(
            model_name="access",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="access", to="sekuracore.employee"
            ),
        ),
        migrations.AddIndex(
            model_name="access",
            index=models.Index(fields=["agent"], name="sekuracore__agent_i_cca86a_idx"),
        ),
        migrations.AddIndex(
            model_name="access",
            index=models.Index(fields=["employee"], name="sekuracore__employe_3f81c0_idx"),
        ),
    ]
