# Generated by Django 4.0.3 on 2022-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sekuracore", "0002_organization_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="description",
            field=models.CharField(default="unknown", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="integration",
            name="name",
            field=models.CharField(default="unknown", max_length=100),
            preserve_default=False,
        ),
    ]
