# Generated by Django 4.1.2 on 2022-11-11 03:28

from django.db import migrations, models
import sekuracore.models


class Migration(migrations.Migration):

    dependencies = [
        ("sekuracore", "0002_alter_access_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="preshared_secret",
            field=models.CharField(default=sekuracore.models.random_string_100, max_length=100),
        ),
    ]
