# Generated by Django 4.0.3 on 2022-03-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sekuracore", "0003_integration_description_integration_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration_configuration",
                to="sekuracore.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="integration",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="IntegrationConfiguration",
        ),
    ]
