# Generated by Django 4.1.2 on 2022-11-11 03:31

from django.db import migrations, models
import sekuracore.models


class Migration(migrations.Migration):

    dependencies = [
        ("sekuracore", "0003_alter_agent_preshared_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="parameters",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="preshared_secret",
            field=models.CharField(blank=True, default=sekuracore.models.random_string_100, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="secret",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
