# Generated by Django 4.1.2 on 2022-11-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sekuracore", "0005_alter_agent_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="parameters",
            field=models.CharField(blank=True, help_text="Comma-separated fields", max_length=200, null=True),
        ),
    ]
